// Mocks generated by Mockito 5.4.2 from annotations
// in fast_trivia/controller/http/dao/quiz_dao.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fast_trivia/controller/http/dao/quiz_dao.dart' as _i2;
import 'package:fast_trivia/model/quiz.dart' as _i4;
import 'package:fast_trivia/model/quiz.dart';
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QuizDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizDao extends _i1.Mock implements _i2.QuizDao {
  MockQuizDao() {
    _i1.throwOnMissingStub(this);
    _i1.when(getQuestionnaries()).thenAnswer((realInvocation) async {
      await Future.delayed(Duration(seconds: 1));
      return Future.value(<Quiz>[
        Quiz({
          "questionario": {
            "id": 1,
            "titulo": "Natureza brasileira",
            "questoes": [
              {
                "id": 1,
                "titulo": "Florestas brasileiras",
                "pergunta": "Qual o nome da maior floresta brasileira?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Caatinga"},
                  {"id": 2, "titulo": "Cerrado"},
                  {"id": 3, "titulo": "Mata Atlântica"},
                  {"id": 4, "titulo": "Amazônica"}
                ]
              },
              {
                "id": 2,
                "titulo": "Praias brasileiras",
                "pergunta": "Qual estado tem a maior faixa litorânea?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "São Paulo"},
                  {"id": 2, "titulo": "Maranhão"},
                  {"id": 3, "titulo": "Bahia"},
                  {"id": 4, "titulo": "Rio de Janeiro"}
                ]
              }
            ]
          }
        }),
        Quiz({
          "questionario": {
            "id": 2,
            "titulo": "Sistema Solar",
            "questoes": [
              {
                "id": 1,
                "titulo": "Nosso planeta",
                "pergunta":
                    "Do sol à extremidade do sistema, qual o número do nosso planeta?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "8"},
                  {"id": 2, "titulo": "4"},
                  {"id": 3, "titulo": "3"},
                  {"id": 4, "titulo": "9"}
                ]
              },
              {
                "id": 2,
                "titulo": "Os grandalhões",
                "pergunta": "Quais os 2 maiores planetas do nossos sistema?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Marte e Urano"},
                  {"id": 2, "titulo": "Vênus e Júpiter"},
                  {"id": 3, "titulo": "Vênus e Saturno"},
                  {"id": 4, "titulo": "Júpiter e Saturno"}
                ]
              },
              {
                "id": 3,
                "titulo": "Os grandalhões",
                "pergunta": "Quantas luas tem Júpiter?",
                "gabarito": 1,
                "alternativas": [
                  {"id": 1, "titulo": "92"},
                  {"id": 2, "titulo": "3"},
                  {"id": 3, "titulo": "6"},
                  {"id": 4, "titulo": "12"}
                ]
              }
            ]
          }
        }),
        Quiz({
          "questionario": {
            "id": 1,
            "titulo": "Bichos do Brasil",
            "questoes": [
              {
                "id": 1,
                "titulo": "Nossos bichos",
                "pergunta": "Qual animal é símbolo do Brasil?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "Lobo guará"},
                  {"id": 2, "titulo": "Onça pintada"},
                  {"id": 3, "titulo": "Sabiá-laranjeira"},
                  {"id": 4, "titulo": "Arara azul"}
                ]
              },
              {
                "id": 2,
                "titulo": "Nossos bichos",
                "pergunta": "Quais desses animais estão em risco de extinção?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Onça-pintada"},
                  {"id": 2, "titulo": "Anta"},
                  {"id": 3, "titulo": "Mico-leão-dourado"},
                  {"id": 4, "titulo": "Todos"}
                ]
              },
              {
                "id": 3,
                "titulo": "Nossos bichos",
                "pergunta": "Qual o maior mamífero do Brasil?",
                "gabarito": 1,
                "alternativas": [
                  {"id": 1, "titulo": "Anta"},
                  {"id": 2, "titulo": "Onça-pintada"},
                  {"id": 3, "titulo": "Baleia-jubarte"},
                  {"id": 4, "titulo": "Ariranha"}
                ]
              },
              {
                "id": 4,
                "titulo": "Nossos bichos",
                "pergunta": "Qual o bicho mais venenoso?",
                "gabarito": 1,
                "alternativas": [
                  {"id": 1, "titulo": "Jararacuçu"},
                  {"id": 2, "titulo": "Aranha armadeira"},
                  {"id": 3, "titulo": "cobra-coral-verdadeira"},
                  {"id": 4, "titulo": "Jararaca"}
                ]
              },
            ]
          }
        }),
      ]);
    });
  }

  @override
  _i3.Future<List<_i4.Quiz>> getQuestionnaries() => (super.noSuchMethod(
        Invocation.method(
          #getQuestionnaries,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Quiz>>.value(<_i4.Quiz>[]),
      ) as _i3.Future<List<_i4.Quiz>>);
}
