// Mocks generated by Mockito 5.4.2 from annotations
// in fast_trivia/controller/http/dao/quiz_dao.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fast_trivia/controller/http/dao/quiz_dao.dart' as _i2;
import 'package:fast_trivia/model/quiz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:fast_trivia/model/quiz.dart';

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QuizDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizDao extends _i1.Mock implements _i2.QuizDao {
  MockQuizDao() {
    _i1.throwOnMissingStub(this);
    _i1.when(getQuestionnaries()).thenAnswer((realInvocation) async {
      await Future.delayed(Duration(seconds: 2));
      return Future.value(<Quiz>[
        Quiz({
          "questionario": {
            "id": 1,
            "titulo": "Natureza brasileira",
            "questoes": [
              {
                "id": 1,
                "titulo": "Florestas brasileiras",
                "pergunta": "Qual o nome da maior floresta brasileira?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Caatinga"},
                  {"id": 2, "titulo": "Cerrado"},
                  {"id": 3, "titulo": "Mata Atlântica"},
                  {"id": 4, "titulo": "Amazônica"}
                ]
              },
              {
                "id": 2,
                "titulo": "Praias brasileiras",
                "pergunta": "Qual estado tem a maior faixa litorânea?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "São Paulo"},
                  {"id": 2, "titulo": "Maranhão"},
                  {"id": 3, "titulo": "Bahia"},
                  {"id": 4, "titulo": "Rio de Janeiro"}
                ]
              }
            ]
          }
        }),
        Quiz({
          "questionario": {
            "id": 1,
            "titulo": "Natureza brasileira",
            "questoes": [
              {
                "id": 1,
                "titulo": "Florestas brasileiras",
                "pergunta": "Qual o nome da maior floresta brasileira?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Caatinga"},
                  {"id": 2, "titulo": "Cerrado"},
                  {"id": 3, "titulo": "Mata Atlântica"},
                  {"id": 4, "titulo": "Amazônica"}
                ]
              },
              {
                "id": 2,
                "titulo": "Praias brasileiras",
                "pergunta": "Qual estado tem a maior faixa litorânea?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "São Paulo"},
                  {"id": 2, "titulo": "Maranhão"},
                  {"id": 3, "titulo": "Bahia"},
                  {"id": 4, "titulo": "Rio de Janeiro"}
                ]
              }
            ]
          }
        }),
        Quiz({
          "questionario": {
            "id": 1,
            "titulo": "Natureza brasileira",
            "questoes": [
              {
                "id": 1,
                "titulo": "Florestas brasileiras",
                "pergunta": "Qual o nome da maior floresta brasileira?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Caatinga"},
                  {"id": 2, "titulo": "Cerrado"},
                  {"id": 3, "titulo": "Mata Atlântica"},
                  {"id": 4, "titulo": "Amazônica"}
                ]
              },
              {
                "id": 2,
                "titulo": "Praias brasileiras",
                "pergunta": "Qual estado tem a maior faixa litorânea?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "São Paulo"},
                  {"id": 2, "titulo": "Maranhão"},
                  {"id": 3, "titulo": "Bahia"},
                  {"id": 4, "titulo": "Rio de Janeiro"}
                ]
              }
            ]
          }
        }),
        Quiz({
          "questionario": {
            "id": 1,
            "titulo": "Natureza brasileira",
            "questoes": [
              {
                "id": 1,
                "titulo": "Florestas brasileiras",
                "pergunta": "Qual o nome da maior floresta brasileira?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Caatinga"},
                  {"id": 2, "titulo": "Cerrado"},
                  {"id": 3, "titulo": "Mata Atlântica"},
                  {"id": 4, "titulo": "Amazônica"}
                ]
              },
              {
                "id": 2,
                "titulo": "Praias brasileiras",
                "pergunta": "Qual estado tem a maior faixa litorânea?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "São Paulo"},
                  {"id": 2, "titulo": "Maranhão"},
                  {"id": 3, "titulo": "Bahia"},
                  {"id": 4, "titulo": "Rio de Janeiro"}
                ]
              }
            ]
          }
        }),
        Quiz({
          "questionario": {
            "id": 1,
            "titulo": "Natureza brasileira",
            "questoes": [
              {
                "id": 1,
                "titulo": "Florestas brasileiras",
                "pergunta": "Qual o nome da maior floresta brasileira?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Caatinga"},
                  {"id": 2, "titulo": "Cerrado"},
                  {"id": 3, "titulo": "Mata Atlântica"},
                  {"id": 4, "titulo": "Amazônica"}
                ]
              },
              {
                "id": 2,
                "titulo": "Praias brasileiras",
                "pergunta": "Qual estado tem a maior faixa litorânea?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "São Paulo"},
                  {"id": 2, "titulo": "Maranhão"},
                  {"id": 3, "titulo": "Bahia"},
                  {"id": 4, "titulo": "Rio de Janeiro"}
                ]
              }
            ]
          }
        }),
        Quiz({
          "questionario": {
            "id": 1,
            "titulo": "Natureza brasileira",
            "questoes": [
              {
                "id": 1,
                "titulo": "Florestas brasileiras",
                "pergunta": "Qual o nome da maior floresta brasileira?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Caatinga"},
                  {"id": 2, "titulo": "Cerrado"},
                  {"id": 3, "titulo": "Mata Atlântica"},
                  {"id": 4, "titulo": "Amazônica"}
                ]
              },
              {
                "id": 2,
                "titulo": "Praias brasileiras",
                "pergunta": "Qual estado tem a maior faixa litorânea?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "São Paulo"},
                  {"id": 2, "titulo": "Maranhão"},
                  {"id": 3, "titulo": "Bahia"},
                  {"id": 4, "titulo": "Rio de Janeiro"}
                ]
              }
            ]
          }
        }),
        Quiz({
          "questionario": {
            "id": 1,
            "titulo": "Natureza brasileira",
            "questoes": [
              {
                "id": 1,
                "titulo": "Florestas brasileiras",
                "pergunta": "Qual o nome da maior floresta brasileira?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Caatinga"},
                  {"id": 2, "titulo": "Cerrado"},
                  {"id": 3, "titulo": "Mata Atlântica"},
                  {"id": 4, "titulo": "Amazônica"}
                ]
              },
              {
                "id": 2,
                "titulo": "Praias brasileiras",
                "pergunta": "Qual estado tem a maior faixa litorânea?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "São Paulo"},
                  {"id": 2, "titulo": "Maranhão"},
                  {"id": 3, "titulo": "Bahia"},
                  {"id": 4, "titulo": "Rio de Janeiro"}
                ]
              }
            ]
          }
        }),
        Quiz({
          "questionario": {
            "id": 1,
            "titulo": "Natureza brasileira",
            "questoes": [
              {
                "id": 1,
                "titulo": "Florestas brasileiras",
                "pergunta": "Qual o nome da maior floresta brasileira?",
                "gabarito": 4,
                "alternativas": [
                  {"id": 1, "titulo": "Caatinga"},
                  {"id": 2, "titulo": "Cerrado"},
                  {"id": 3, "titulo": "Mata Atlântica"},
                  {"id": 4, "titulo": "Amazônica"}
                ]
              },
              {
                "id": 2,
                "titulo": "Praias brasileiras",
                "pergunta": "Qual estado tem a maior faixa litorânea?",
                "gabarito": 3,
                "alternativas": [
                  {"id": 1, "titulo": "São Paulo"},
                  {"id": 2, "titulo": "Maranhão"},
                  {"id": 3, "titulo": "Bahia"},
                  {"id": 4, "titulo": "Rio de Janeiro"}
                ]
              }
            ]
          }
        }),
      ]);
    });
  }

  @override
  _i3.Future<List<_i4.Quiz>> getQuestionnaries() => (super.noSuchMethod(
        Invocation.method(
          #getQuestionnaries,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Quiz>>.value(<_i4.Quiz>[]),
      ) as _i3.Future<List<_i4.Quiz>>);
}
